import streamlit as st

st.set_page_config(page_title="Heritage Housing", page_icon="📈")

st.write("## Heritage Housing Dashboard!")

st.sidebar.success("Project Summary.")

st.markdown("""
#### Business Requirements

The dashboard application that allows her to maximize sale price of her inherited houses as well as any other houses. The dashboard should includes 
- prediction of house sale prices from her 4 inherited houses, and any other house in Ames, Iowa. The prediction should be generated by a reliable ML system.  
- data visualizations of training data that shows correlations of the properties of houses against the sale price. It is sufficient to use conventional data analysis techniques.
- A way to explain the predictions made by the estimator. The estimator should demonstrate an R2 score of at least 0.75 on the training and the test data.
- Hypothesis used in the project and how it has been validated

#### Project Dataset

The dataset used in this project is a curated dataset of publicly available Ames Housing dataset. 
The dataset contains 24 explanatory variables describing key aspect of residential homes in Ames, Iowa. 
It contains unique records of 1430 houses and 81 variables.
The dataset can be downloaded from [here](https://www.kaggle.com/datasets/codeinstitute/housing-prices-data).
""")
